version: '3.9'
services: 
    db:
        image: mongo
        container_name: db
        restart: always
        environment: 
            -MONGO_INITDB_USERNAME-dio
            -MONGO_INITDV_ROOT_PASSWORD=dio
        ports: 
            "27017:27017"
        volumes: 
            -/Users/010987631/DIO/dbdata:/data/db